// <auto-generated />
using System;
using Backend_asp.net.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_asp.net.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20251023221032_Edit_Relationship_RoverMech")]
    partial class Edit_Relationship_RoverMech
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_asp.net.Models.RoverMech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandRoverMech")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelRoverMech")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomerRoveryShop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoverGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RoverMechTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoveryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.HasIndex("UserRoveryId");

                    b.ToTable("roverMechs");
                });

            modelBuilder.Entity("Backend_asp.net.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserRoveryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoveryId");

                    b.ToTable("shoppingCarts");
                });

            modelBuilder.Entity("Backend_asp.net.Models.UserRovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bilding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeCreateUserRovery")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("userRoverys");
                });

            modelBuilder.Entity("Backend_asp.net.Models.RoverMech", b =>
                {
                    b.HasOne("Backend_asp.net.Models.ShoppingCart", null)
                        .WithMany("RoverMeches")
                        .HasForeignKey("ShoppingCartId");

                    b.HasOne("Backend_asp.net.Models.UserRovery", "UserRovery")
                        .WithMany("Mech")
                        .HasForeignKey("UserRoveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRovery");
                });

            modelBuilder.Entity("Backend_asp.net.Models.ShoppingCart", b =>
                {
                    b.HasOne("Backend_asp.net.Models.UserRovery", "UserRovery")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserRoveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRovery");
                });

            modelBuilder.Entity("Backend_asp.net.Models.ShoppingCart", b =>
                {
                    b.Navigation("RoverMeches");
                });

            modelBuilder.Entity("Backend_asp.net.Models.UserRovery", b =>
                {
                    b.Navigation("Mech");

                    b.Navigation("ShoppingCarts");
                });
#pragma warning restore 612, 618
        }
    }
}
